### ISSUE TITLE
another bad string

### ISSUE THREAD

**Issue by potato404** [n1klas4008/poe-regex#58]
"!t \d+|hey|ns d|olati|xa|s u|rege|ss r|s arm"

mods to avoid are

- drowing orbs
- exarch runes
- tentacle fiends
- awakeners desolation
- reflect
- players and their minions deal no damage 3 out of every 10 seconds
- players are targeted by a meteor when they use a flask
- players have reduced action speed for each time they've used a skill recently
- rare monsters have volatile cores
- cant not regen
- less recovery of life and energy shield
- less armour and reduced block chance

Item Class: Maps
Rarity: Rare
Brutal Haven
Sanctuary Map
--------
Map Tier: 17
Item Quantity: +135% (augmented)
Item Rarity: +69% (augmented)
Monster Pack Size: +52% (augmented)
More Maps: +60% (augmented)
More Currency: +109% (augmented)
Quality: +20% (augmented)
--------
Item Level: 84
--------
Monster Level: 84
--------
{ Prefix Modifier "Grasping" (Tier: 1) }
Monsters inflict 2 Grasping Vines on Hit
(Up to 10 Vines can grasp you, inflicting 8% less Movement Speed per Vine. Broken by moving)
{ Prefix Modifier "Armoured" — Physical }
+40% Monster Physical Damage Reduction
{ Prefix Modifier "Valdo's" (Tier: 1) }
Rare monsters in area are Shaper-Touched
{ Suffix Modifier "of Defiance" (Tier: 1) }
Debuffs on Monsters expire 100% faster
{ Suffix Modifier "of Elemental Weakness" — Caster, Curse }
Players are Cursed with Elemental Weakness
(Elemental Weakness is a Hex which inficts -15% to all Elemental Resistances. It lasts 8 seconds)
{ Suffix Modifier "of Ice" }
Area has patches of Chilled Ground
(You are Chilled while standing in Chilled Ground)
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
--------
Modifiable only with Chaos Orbs, Vaal Orbs, Delirium Orbs and Chisels

![image](https://github.com/user-attachments/assets/10d49831-9f28-465f-a03d-e778cf75b619)

**Comment by n1klas4008** [comment]
thank you for reporting this, the issue here is `t \d+` for the reflect mods which also matches this mod `Monsters inflict 2 Grasping Vines on Hit` it basically means t followed by a space and number which is the case here with `t 2`

currently the T17 reflect mod gets shortened to `t \d+` (5 characters) but causes issues.
to prevent this from happening again I added the problematic strings to the blacklist

```
t #
t 2
2 g
```
this results in the T17 reflect mod giving `s ref` (4 characters).... how.. it should also be 5?


thanks to your report I noticed I was accounting `#` which gets replaced into `\d+` as 2 rather than 3 characters - additionally the grasping vine mod used to land on either `t 2` or `2 g` having both of those blacklisted it now lands on `pin` which is also 3 characters.


once again thanks for the report, this can only be improved with reports like these!
