### ISSUE TITLE
Corrupted option simplification and possible bug

### ISSUE THREAD

**Issue by levlazarev** [n1klas4008/poe-regex#66]
**Is your feature request related to a problem? Please describe.**
Yes and no. The include option is adding "pte" to string so any uncorrupted maps are excluded even if they match modifier options selected.  Exclude generated a blank string and when I hit generate again it appears to have gotten stuck on the crunching numbers loading screen.

**Describe the idea/solution you'd like**
An allow corrupted maps yes/no option might be better/more intuitive with the no option appending "!pte"

**Describe alternatives you've considered**
A more complicated approach might be a filter option to include corrupted maps above certain quality/rarity/pack size thresholds independently of the global thresholds but that seems a little overkill.

**Additional context**
In the 5-10 minutes I've spent writing this the exclude > generate is still stuck on crunching numbers. May at least need to look at what exclude is trying to do as it seems to be stuck in a loop.

![image](https://github.com/user-attachments/assets/379bf901-232a-4d0e-8eec-4f3e55686142)

**Comment by levlazarev** [comment]
Additional troubleshooting info: Crunching numbers loop can be broken by refreshing but if you generate again it goes back to looping.

**Comment by n1klas4008** [comment]
will look into this, thanks alot for the report!

**Comment by n1klas4008** [comment]
there is a 100ms delay between the animation going off and it being turned off because I coudnt get it to work otherwise, the issue here is that whilst you click generate it still has the regex in its cache and is returned instantly before the 100ms, so the overlay is getting disabled before it even gets shown.

I have investigated this further, when nothing is selected hitting Generate causes the same issue.
will figure out how to fix this now - the page itself is functioning just the visual isnt updating accordingly

**Comment by n1klas4008** [comment]
the modal is only getting disabled when the checkbox to calculate on generate is ticked..
I'll remove that condition which should solve that issue.

regarding the other thing mentioned to have a simple Yes/No for Corrupted Maps;
my suggested idea is to reword the "Include" label to say "Force", the "Exclude" Label to "Block" and the Ignore Label remains as Ignore.

**Comment by n1klas4008** [comment]
this should be resolved now, thanks again for the report!
